version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      JWT_SECRET: ''
      DATABASE_URL: "postgresql://robot_be_user:ZTE2023*am@181.48.233.115:5432/robot_be_db"
      MINIO_USERNAME: "robot_be_admin"
      MINIO_PASSWORD: "f8fc9ee4a6b7cfbf055bb37a0f056469ec664efabf666780e96f88a21e081c922e8d3423f3236c5ed7601a32400ecc3ac43b54b20dc17a3e11cd6b67126f04f1"
      MINIO_ENDPOINT: "181.48.233.115"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "ya9NK2dz68KZPOOLRCuy"
      MINIO_SECRET_KEY: "W8sgovidWSGGXLz0Tar2tDI0CWIPpOYFrEMvXnWF"
      PUBLIC_IP_OLT_SSH: "200.118.2.69"
      OLT_SSH_USERNAME: "noc"
      OLT_SSH_PASSWORD: "Nocr3s1"
      OLT_SSH_USER: "ec6040d"
      OLT_SSH_PASS: "Claro2023*"
    volumes:
      - /home/daniel/ssl:/app/ssl  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/daniel/ssl:/etc/nginx/ssl 

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "robot_be_admin"
      MINIO_ROOT_PASSWORD: "f8fc9ee4a6b7cfbf055bb37a0f056469ec664efabf666780e96f88a21e081c922e8d3423f3236c5ed7601a32400ecc3ac43b54b20dc17a3e11cd6b67126f04f1"
      MINIO_KMS_KES_URL: "https://minio:9000"  # Use the container name for HTTPS communication
      MINIO_KMS_KES_SECURE: "on"
      MINIO_KMS_KES_INSECURE: "off"
    volumes:
      - /home/daniel/automation/data:/data   # Assuming this is where MinIO data is stored
      - /home/daniel/ssl/certificate.crt:/root/.minio/certs/public.crt:ro
      - /home/daniel/ssl/private.key:/root/.minio/certs/private.key:ro
      - /home/daniel/ssl/ca_bundle.crt:/root/.minio/certs/CAs/ca.crt:ro
    command: server --address ":9000" --console-address ":9001" /data
    